// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package dataproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestData struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestData) Reset()         { *m = RequestData{} }
func (m *RequestData) String() string { return proto.CompactTextString(m) }
func (*RequestData) ProtoMessage()    {}
func (*RequestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0}
}

func (m *RequestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestData.Unmarshal(m, b)
}
func (m *RequestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestData.Marshal(b, m, deterministic)
}
func (m *RequestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestData.Merge(m, src)
}
func (m *RequestData) XXX_Size() int {
	return xxx_messageInfo_RequestData.Size(m)
}
func (m *RequestData) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestData.DiscardUnknown(m)
}

var xxx_messageInfo_RequestData proto.InternalMessageInfo

func (m *RequestData) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type ResponseData struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseData) Reset()         { *m = ResponseData{} }
func (m *ResponseData) String() string { return proto.CompactTextString(m) }
func (*ResponseData) ProtoMessage()    {}
func (*ResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{1}
}

func (m *ResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseData.Unmarshal(m, b)
}
func (m *ResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseData.Marshal(b, m, deterministic)
}
func (m *ResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseData.Merge(m, src)
}
func (m *ResponseData) XXX_Size() int {
	return xxx_messageInfo_ResponseData.Size(m)
}
func (m *ResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseData proto.InternalMessageInfo

func (m *ResponseData) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestData)(nil), "dataproto.requestData")
	proto.RegisterType((*ResponseData)(nil), "dataproto.responseData")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor_871986018790d2fd) }

var fileDescriptor_871986018790d2fd = []byte{
	// 130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x49, 0x2c, 0x49,
	0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x04, 0xb1, 0xc1, 0x4c, 0x25, 0x45, 0x2e, 0xee,
	0xa2, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x97, 0xc4, 0x92, 0x44, 0x21, 0x21, 0x2e, 0x16, 0x90,
	0x9c, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x98, 0xad, 0xa4, 0xc4, 0xc5, 0x53, 0x94, 0x5a,
	0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x8a, 0x4b, 0x8d, 0x91, 0x17, 0x17, 0x7b, 0x7a, 0x2a, 0xc4, 0x08,
	0x7b, 0x2e, 0xae, 0xa2, 0xd4, 0x92, 0xd2, 0xa2, 0x3c, 0x30, 0x4f, 0x4c, 0x0f, 0x6e, 0x97, 0x1e,
	0x92, 0x45, 0x52, 0xe2, 0x28, 0xe2, 0x08, 0xd3, 0x95, 0x18, 0x9c, 0xb8, 0xa3, 0x10, 0xee, 0x4b,
	0x62, 0x03, 0x53, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x93, 0xed, 0x52, 0x63, 0xbf, 0x00,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GetDataClient is the client API for GetData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GetDataClient interface {
	ReturnData(ctx context.Context, in *RequestData, opts ...grpc.CallOption) (*ResponseData, error)
}

type getDataClient struct {
	cc *grpc.ClientConn
}

func NewGetDataClient(cc *grpc.ClientConn) GetDataClient {
	return &getDataClient{cc}
}

func (c *getDataClient) ReturnData(ctx context.Context, in *RequestData, opts ...grpc.CallOption) (*ResponseData, error) {
	out := new(ResponseData)
	err := c.cc.Invoke(ctx, "/dataproto.getData/returnData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetDataServer is the server API for GetData service.
type GetDataServer interface {
	ReturnData(context.Context, *RequestData) (*ResponseData, error)
}

// UnimplementedGetDataServer can be embedded to have forward compatible implementations.
type UnimplementedGetDataServer struct {
}

func (*UnimplementedGetDataServer) ReturnData(ctx context.Context, req *RequestData) (*ResponseData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReturnData not implemented")
}

func RegisterGetDataServer(s *grpc.Server, srv GetDataServer) {
	s.RegisterService(&_GetData_serviceDesc, srv)
}

func _GetData_ReturnData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetDataServer).ReturnData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dataproto.getData/ReturnData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetDataServer).ReturnData(ctx, req.(*RequestData))
	}
	return interceptor(ctx, in, info, handler)
}

var _GetData_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dataproto.getData",
	HandlerType: (*GetDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "returnData",
			Handler:    _GetData_ReturnData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data.proto",
}
